version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11.4
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Building application..."
      - python3 api.py
      # Optionally, you can run any additional build commands here
artifacts:
  files:
    - '**/*'
  discard-paths: yes
